export const POPULAR_TICKERS = [
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corporation' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation' },
  { ticker: 'META', name: 'Meta Platforms Inc.' },
  { ticker: 'TSLA', name: 'Tesla Inc.' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway' },
  { ticker: 'LLY', name: 'Eli Lilly and Company' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation' },
  { ticker: 'MA', name: 'Mastercard Inc.' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'HD', name: 'The Home Depot' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'MRK', name: 'Merck & Co.' },
  { ticker: 'ABBV', name: 'AbbVie Inc.' },
  { ticker: 'CVX', name: 'Chevron Corporation' },
  { ticker: 'KO', name: 'The Coca-Cola Company' },
  { ticker: 'PEP', name: 'PepsiCo Inc.' },
  { ticker: 'BAC', name: 'Bank of America' },
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'MCD', name: "McDonald's Corporation" },
  { ticker: 'CSCO', name: 'Cisco Systems' },
  { ticker: 'DIS', name: 'The Walt Disney Company' },
  { ticker: 'NFLX', name: 'Netflix Inc.' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'CRM', name: 'Salesforce Inc.' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'INTC', name: 'Intel Corporation' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.' },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'ORCL', name: 'Oracle Corporation' },
  { ticker: 'IBM', name: 'IBM Corporation' },
  { ticker: 'GE', name: 'GE Aerospace' },
  { ticker: 'CAT', name: 'Caterpillar Inc.' },
  { ticker: 'BA', name: 'Boeing Company' },
  { ticker: 'GS', name: 'Goldman Sachs' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'WFC', name: 'Wells Fargo' },
  { ticker: 'C', name: 'Citigroup Inc.' },
  { ticker: 'AMGN', name: 'Amgen Inc.' },
  { ticker: 'GILD', name: 'Gilead Sciences' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb' },
  { ticker: 'PFE', name: 'Pfizer Inc.' },
  { ticker: 'MRNA', name: 'Moderna Inc.' },
  { ticker: 'SQ', name: 'Block Inc.' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'UBER', name: 'Uber Technologies' },
  { ticker: 'LYFT', name: 'Lyft Inc.' },
  { ticker: 'ABNB', name: 'Airbnb Inc.' },
  { ticker: 'SNAP', name: 'Snap Inc.' },
  { ticker: 'TWTR', name: 'Twitter / X' },
  { ticker: 'SPOT', name: 'Spotify Technology' },
  { ticker: 'SHOP', name: 'Shopify Inc.' },
  { ticker: 'ZM', name: 'Zoom Video Communications' },
  { ticker: 'PLTR', name: 'Palantir Technologies' },
  { ticker: 'RBLX', name: 'Roblox Corporation' },
  { ticker: 'COIN', name: 'Coinbase Global' },
  { ticker: 'HOOD', name: 'Robinhood Markets' },
  { ticker: 'SOFI', name: 'SoFi Technologies' },
  { ticker: 'NKE', name: 'Nike Inc.' },
  { ticker: 'SBUX', name: 'Starbucks Corporation' },
  { ticker: 'TGT', name: 'Target Corporation' },
  { ticker: 'F', name: 'Ford Motor Company' },
  { ticker: 'GM', name: 'General Motors' },
  { ticker: 'RIVN', name: 'Rivian Automotive' },
  { ticker: 'LCID', name: 'Lucid Group' },
  { ticker: 'NIO', name: 'NIO Inc.' },
  { ticker: 'BIDU', name: 'Baidu Inc.' },
  { ticker: 'BABA', name: 'Alibaba Group' },
  { ticker: 'JD', name: 'JD.com Inc.' },
  { ticker: 'TCEHY', name: 'Tencent Holdings' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor' },
  { ticker: 'ASML', name: 'ASML Holding' },
  { ticker: 'SAP', name: 'SAP SE' },
  { ticker: 'TM', name: 'Toyota Motor' },
  { ticker: 'SONY', name: 'Sony Group' },
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock ETF' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF' },
  { ticker: 'GLD', name: 'SPDR Gold Shares' },
  { ticker: 'SLV', name: 'iShares Silver Trust' },
  { ticker: 'USO', name: 'United States Oil Fund' },
]

export function searchTickers(query) {
  if (!query || query.length < 1) return []
  const q = query.toUpperCase()
  return POPULAR_TICKERS.filter(
    t => t.ticker.startsWith(q) || t.name.toUpperCase().includes(q)
  ).slice(0, 6)
}
